### ISSUE TITLE
도메인 Entity 구축

### ISSUE THREAD

**Issue by hyunjungjeon** [Purple-Print/network-server#13]
**문제 제기**
- 도메인 Entity 구축을 하기 위해

**기능 요약**
- 도메인 별 Entity 구축

**기능 설명**
- 회원, 연극, 편집, 게시, 신고 컨텍스트 Entity 구축

**할일 목록**
- 해당 기능을 개발하기 위해 수행해야 할 하위 업무를 to-do list 형식으로 작성해주세요 ( 단축키 - [ ] )
- [x] Entity  구축

**비고**

**Comment by yee950419** [comment]
완료했습니다
