### ISSUE TITLE
character 도메인 - 캐릭터 파일 확장자 예외 처리 추가

### ISSUE THREAD

**Issue by yee950419** [Purple-Print/network-server#131]
**문제 제기**
- 캐릭터 파일 확장자 예외 처리 추가

**기능 요약**
- 캐릭터 파일 확장자 예외 처리 추가

**기능 설명**
- 캐릭터 파일 확장자 예외 처리 추가

**할일 목록**
- [x] 캐릭터 파일 확장자 예외 처리 추가

**Comment by hyunjungjeon** [comment]
이슈완료했습니다
