### ISSUE TITLE
IntelliJ 개발 환경 세팅

### ISSUE THREAD

**Issue by hyunjungjeon** [Purple-Print/network-server#14]
**문제 제기**
- 백엔드 서버 개발을 위한 IntelliJ 개발 환경 세팅 필요

**기능 요약**
- IntelliJ 개발 환경 세팅

**기능 설명**
- IntelliJ spring boot 개발 환경 세팅과 개발 환경 공유 github  업로드

**할일 목록**
- 해당 기능을 개발하기 위해 수행해야 할 하위 업무를 to-do list 형식으로 작성해주세요 ( 단축키 - [ ] )
- [x] IntelliJ 개발 환경 세팅
- [x] GitHub 업로드

**비고**
-

**Comment by yee950419** [comment]
세팅 완료했습니다
