### ISSUE TITLE
회원 도메인 - 회원가입 api 구축

### ISSUE THREAD

**Issue by yee950419** [Purple-Print/network-server#19]
**문제 제기**
- 회원가입

**기능 요약**
- 패키지 구조 및 회원가입

**기능 설명**
- 회원가입

**할일 목록**
- [x] 패키지 구조 잡기
- [x] 회원가입
- [x] 아이디 중복 확인
- [x] 이메일 인증

**Comment by hyunjungjeon** [comment]
이슈 완료했습니다.
