### ISSUE TITLE
test

### ISSUE THREAD

**Issue by yee950419** [Purple-Print/network-server#4]
**문제 제기**
- 이벤트 스토밍

**기능 요약**
- Domain Event Deduction
- External System Deduction
- Command Deduction
- HotSpot Deduction
- Actor Deduction
- Aggregate Deduction
- Bounded Context Deduction
- Policy Deduction
- Snap - E

**기능 설명**
- DDD 이벤트 스토밍 설계

**할일 목록**
- [x] Domain Event Deduction
- [x] External System Deduction
- [x] Command Deduction
- [x] HotSpot Deduction
- [x] Actor Deduction
- [x] Aggregate Deduction
- [x] Bounded Context Deduction
- [x] Policy Deduction
- [x] Snap - E

**비고**
-

**Comment by hyunjungjeon** [comment]
https://miro.com/app/board/uXjVPMwtP40=/

이슈 완료했습니다.
