### ISSUE TITLE
캐릭터 도메인 - 캐릭터 추천

### ISSUE THREAD

**Issue by hyunjungjeon** [Purple-Print/network-server#41]
**문제 제기**
- 사용자는 캐릭터를 생성할 수 있다.

**기능 요약**
- 캐릭터 생성 api

**기능 설명**
- xr 통신, ai 통신

**할일 목록**
- [x] xr 통신으로 사용자 이미지 가져오기
- [x] ai 통신으로 사용자와 유사한 캐릭터 추천 연결

**Comment by yee950419** [comment]
완료했습니다
