### ISSUE TITLE
캐릭터 도메인 - 캐릭터 생성 api 구축

### ISSUE THREAD

**Issue by hyunjungjeon** [Purple-Print/network-server#42]
**문제 제기**
- 사용자는 캐릭터를 생성할 수 있다.

**기능 요약**
- 캐릭터 생성 api 구축

**기능 설명**
- 캐릭터 생성 api 구축

**할일 목록**
- [x] 캐릭터 생성 api

**Comment by yee950419** [comment]
완료했습니다.
